export enum ErrorCodes {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  NO_PRODUCT_TO_SIMULATE = 'NO_PRODUCT_TO_SIMULATE',
  CURRENCIES_SERVER_UNAVAILABLE = 'CURRENCIES_SERVER_UNAVAILABLE',
  CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
}
