export enum ErrorCodes {
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  NO_PRODUCT_TO_SIMULATE = 'NO_PRODUCT_TO_SIMULATE',
  CURRENCIES_SERVER_UNAVAILABLE = 'CURRENCIES_SERVER_UNAVAILABLE',
  CURRENCY_NOT_FOUND = 'CURRENCY_NOT_FOUND',
  USER_NOT_FOUND = 'user-not-found',
  BAD_CREDENTIALS = 'bad-credentials',
  EMAIL_ALREADY_EXIST_BAD_REQUEST = 'email-already-exist-bad-request',
  USER_BLOCKED_UNAUTHORIZED = 'user-blocked-unauthorized',
  USER_NOT_ENABLED_UNAUTHORIZED = 'user-not-enabled-unauthorized',
  USER_ALREADY_ENABLED_UNAUTHORIZED = 'user-already-enabled-unauthorized',
  INVALID_TOKEN_UNAUTHORIZED = 'invalid-token-unauthorized',
  INVALID_JWT_FORMAT = 'invalid-jwt-format',
  DECLARATION_NOT_FOUND = 'declaration-not-found',
  DECLARATION_STATUS_CHANGE_FORBIDDEN = 'declaration-status-change-forbidden',
}
