export enum ResponseCodes {
  USER_CREATED = 'user-created',
  USER_EMAIL_VALIDATED = 'user-email-validated',
  USER_ASK_EMAIL_VALIDATION = 'user-ask-email-validation',
  USER_ASK_UPDATE_EMAIL = 'user-ask-update-email',
  USER_ASK_RESET_PASSWORD = 'user-ask-reset-password',
  USER_EMAIL_UPDATED = 'user-email-updated',
  USER_PASSWORD_RESET = 'user-password-reset',
  USER_PASSWORD_UPDATED = 'user-password-updated',
  DECLARATION_STATUS_UPDATED = 'declaration-status-updated',
  SEARCH_PRODUCT_HISTORY_UPDATED = 'search-product-history-updated',
  DECLARATION_UPDATED = 'declaration-updated',
  CURRENCIES_UPDATED = 'currency-updated',
  FEEDBACK_UPDATED = 'feedback-updated',
  FAVORITE_ADDED = 'favorite-added',
  FAVORITE_DELETED = 'favorite-deleted',
  DEFAULT_COUNTRY_UPDATED = 'default-country-updated',
}
