name: Delta V - back

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Job to run."
        required: true
        default: "prod-deploy"
  pull_request:
    paths:
      - back/**
  push:
    branches:
      - develop
      - master
    paths:
      - back/**

jobs:
  test-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    env:
      PORT: 8080
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB_DATABASE: postgres

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1
        with:
          postgresql version: "13"
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: pass
      - run: "yarn install --ignore-scripts"
      - run: yarn migration:run
      - run: yarn lint
      - run: yarn test

  deploy-back-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'prod-deploy'}}
    # if: github.ref == 'refs/heads/master'
    needs: test-back
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1
        with:
          timeout: 1800
          alias: delta-v-back-prod
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
