name: Delta V - front

on:
  pull_request:
    paths:
      - front/**
  push:
    branches:
      - develop
      - master
    paths:
      - front/**

jobs:
  test-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    env:
      PORT: 8080
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB_DATABASE: postgres

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1
        with:
          postgresql version: "13"
          postgresql db: postgres
          postgresql user: postgres
          postgresql password: pass
      - run: yarn
      - run: yarn lint

  deploy-front-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test-front
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1
        with:
          alias: delta-v-front-prod
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
