name: Delta V - front

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Job to run."
        required: true
        default: "stage-deploy"
  pull_request:
    paths:
      - front/**
  push:
    branches:
      - develop
      - master
    paths:
      - front/**

jobs:
  test-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: "yarn install --ignore-scripts"
      - run: yarn lint
      - run: yarn jest
      - run: yarn build

  deploy-front-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: test-front
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          timeout: 1800
          alias: delta-v-front-stage
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

  deploy-front-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test-front
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          timeout: 1800
          alias: delta-v-front-prod
          force: true
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
