name: Delta V - front

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Job to run."
        required: true
        default: "prod-deploy"
  pull_request:
    paths:
      - front/**
  push:
    branches:
      - develop
      - master
    paths:
      - front/**

jobs:
  test-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    env:
      PORT: 8080
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pass
      DB_DATABASE: postgres

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: "yarn install --ignore-scripts"
      - run: yarn lint

  deploy-front-production:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.job == 'prod-deploy'}}
    # if: github.ref == 'refs/heads/master'
    needs: test-front
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@master
        with:
          timeout: 1800
          alias: delta-v-front-prod
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
