name: Test clever cloud

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  test-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn lint
      - run: yarn test

  deploy-back-production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: test-back
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: 47ng/actions-clever-cloud@v1
        with:
          alias: delta-v-back-prod
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}
